<template>
	<div id="rankbanner">
		<select text-align="center" 
		v-for="(item,index) in selectList" 
		v-bind:name="item.selectname"
		v-on:change="getVal(index)"
		>
			<option v-for="btn in item.option" v-bind:value="btn.value">
				{{btn.text}}
			</option>
		</select>
	</div>
</template>
<script>
import film from "@/router/film"
	export default{
		name:"rang-banner",
		film,
		data:function(){
			return {
				selectList:[
					//评分高低
					{
						selectname:"film_info",
						selectType:"评分高低",
						option:[
						{
							value:"评分高低",
							text:"评分高低"
						},
						{
							value:"评分最高",
							text:"评分最高"
						},
						{
							value:"评分最低",
							text:"评分最低"
						}]
					},

					//电影类别
					{
						selectname:"film_type",
						selectType:"电影类型",
						option:[
						{
							value:"电影类型",
							text:"电影类型"
						},
						{
							value:"爱情",
							text:"爱情"
						},
						{
							value:"喜剧",
							text:"喜剧"
						},
						{
							value:"剧情",
							text:"剧情"
						},
						{
							value:"动画",
							text:"动画"
						},
						{
							value:"科幻",
							text:"科幻"
						},
						{
							value:"动作",
							text:"动作"
						},
						{
							value:"经典",
							text:"经典"
						},
						{
							value:"悬疑",
							text:"悬疑"
						},
						{
							value:"青春",
							text:"青春"
						},
						{
							value:"犯罪",
							text:"犯罪"
						},
						{
							value:"惊悚",
							text:"惊悚"
						},
						{
							value:"文艺",
							text:"文艺"
						},
						{
							value:"搞笑",
							text:"搞笑"
						},
						{
							value:"纪录片",
							text:"纪录片"
						},
						{
							value:"励志",
							text:"励志"
						},
						{
							value:"恐怖",
							text:"恐怖"
						},
						{
							value:"战争",
							text:"战争"
						},
						{
							value:"短片",
							text:"短片"
						},
						{
							value:"黑色幽默",
							text:"黑色幽默"
						},
						{
							value:"魔幻",
							text:"魔幻"
						},
						{
							value:"传奇",
							text:"传奇"
						},
						{
							value:"情色",
							text:"情色"
						},
						{
							value:"感人",
							text:"感人"
						},
						{
							value:"暴力",
							text:"暴力"
						},
						{
							value:"家庭",
							text:"家庭"
						},
						{
							value:"音乐",
							text:"音乐"
						},
						{
							value:"动画短片",
							text:"动画短片"
						},
						{
							value:"童年",
							text:"童年"
						},
						{
							value:"浪漫",
							text:"浪漫"
						},
						{
							value:"女性",
							text:"女性"
						},
						{
							value:"黑帮",
							text:"黑帮"
						},
						{
							value:"同志",
							text:"同志"
						},
						{
							value:"烂片",
							text:"烂片"
						},
						{
							value:"史诗",
							text:"史诗"
						},
						{
							value:"童话",
							text:"童话"
						},
						{
							value:"西部",
							text:"西部"
						},
						]
					},

					//国家/地区
					{
						selectname:"film_area",
						selectType:"国家地区",
						option:[
						{
							value:"国家地区",
							text:"国家地区"
						},
						{
							value:"中国",
							text:"中国"
						},
						{
							value:"香港",
							text:"香港"
						},
						{
							value:"台湾",
							text:"台湾"
						},
						{
							value:"中国大陆",
							text:"中国大陆"
						},
						{
							value:"美国",
							text:"美国"
						},
						{
							value:"韩国",
							text:"韩国"
						},
						{
							value:"法国",
							text:"法国"
						},
						{
							value:"日本",
							text:"日本"
						},
						{
							value:"英国",
							text:"英国"
						},
						{
							value:"德国",
							text:"德国"
						},
						{
							value:"意大利",
							text:"意大利"
						},
						{
							value:"印度",
							text:"印度"
						},
						{
							value:"西班牙",
							text:"西班牙"
						},
						{
							value:"泰国",
							text:"泰国"
						},
						{
							value:"欧洲",
							text:"欧洲"
						},
						{
							value:"加拿大",
							text:"加拿大"
						},
						{
							value:"澳大利亚",
							text:"澳大利亚"
						},
						{
							value:"俄罗斯",
							text:"俄罗斯"
						},
						{
							value:"伊朗",
							text:"伊朗"
						},
						{
							value:"瑞典",
							text:"瑞典"
						},
						{
							value:"爱尔兰",
							text:"爱尔兰"
						},
						{
							value:"巴西",
							text:"巴西"
						},
						{
							value:"丹麦",
							text:"丹麦"
						},
						{
							value:"波兰",
							text:"波兰"
						},
						{
							value:"捷克",
							text:"捷克"
						},
						{
							value:"阿根廷",
							text:"阿根廷"
						},
						{
							value:"比利时",
							text:"比利时"
						},
						{
							value:"墨西哥",
							text:"墨西哥"
						},
						{
							value:"新西兰",
							text:"新西兰"
						},
						{
							value:"荷兰",
							text:"荷兰"
						},
						{
							value:"奥地利",
							text:"奥地利"
						},
						{
							value:"土耳其",
							text:"土耳其"
						},
						{
							value:"匈牙利",
							text:"匈牙利"
						},
						{
							value:"瑞士",
							text:"瑞士"
						},
						{
							value:"以色列",
							text:"以色列"
						}
						]
					},

					//年代
					{
						selectname:"film_year",
						selectType:"所属年代",
						option:[
						{
							value:"所属年代",
							text:"所属年代"
						},
						{
							value:"2016",
							text:"2016"
						},
						{
							value:"2015",
							text:"2015"
						},
						{
							value:"2014",
							text:"2014"
						},
						{
							value:"2013",
							text:"2013"
						},
						{
							value:"2012",
							text:"2012"
						},
						{
							value:"2011",
							text:"2011"
						},
						{
							value:"2010",
							text:"2010"
						},
						{
							value:"2009",
							text:"2009"
						},
						{
							value:"2008",
							text:"2008"
						},
						{
							value:"2007",
							text:"2007"
						},
						{
							value:"2006",
							text:"2006"
						},
						{
							value:"2005",
							text:"2005"
						},
						{
							value:"2004",
							text:"2004"
						},
						{
							value:"2003",
							text:"2003"
						},
						{
							value:"2002",
							text:"2002"
						},
						{
							value:"2001",
							text:"2001"
						},
						{
							value:"2000",
							text:"2000"
						},
						{
							value:"1999",
							text:"1999"
						},
						{
							value:"1998",
							text:"1998"
						},
						{
							value:"1997",
							text:"1997"
						},
						{
							value:"1996",
							text:"1996"
						},
						{
							value:"1995",
							text:"1995"
						},
						{
							value:"1994",
							text:"1994"
						},
						{
							value:"1993",
							text:"1993"
						},
						{
							value:"1992",
							text:"1992"
						},
						{
							value:"1991",
							text:"1991"
						},
						{
							value:"1990",
							text:"1990"
						},
						{
							value:"1989",
							text:"1989"
						},
						{
							value:"1988",
							text:"1988"
						}
						]
					},
				],
			}
		},
		methods:{
			getVal:function(index){
				var sval=document.querySelectorAll("#rankbanner select")[index].value;
				if((sval!='国家地区')&&(sval!='评分高低')&&(sval!='电影类型')&&(sval!='所属年代')){//value不等于最开始的初始值
					film.dispatch("getSelectVal",sval)
				}
			},
		}
	}
</script>
<style>	
	#rankbanner{
		padding: 1% 0;
		height: 36px;
		display: flex;
		vertical-align: center
	}
	#rankbanner select{
		position: relative;
		flex:1;
		padding: 3px 0 3px 1%;
		margin: 0 2px;
		width: 24%;
		text-align: center;
		border-radius: 4px;
		font-size: 1.5rem;
	}
	#rankbanner select:after{
		content:"";
		display: inline-block;
		border:1px solid black;
		width: 5px;
		height:5px;
	}
</style>